// tslint:disable
/**
 * ValkyrAI CORE API
 * The API for accessing ValkyrAI services
 *
 * The version of the OpenAPI document: 0.9.25
 * Contact: info@valkyrlabs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../src/runtime';

// thorapi

/**
 * System ID of the ACL
 * @export
 * @interface AclSid
 */
export type AclSid  = {
    /**
     * 
     * @type {string}
     * @memberof AclSid
     */
    sid?: string;
    /**
     * 
     * @type {string}
     * @memberof AclSid
     */
    principal?: string;
    /**
     * Unique identifier for object in the system
     * @type {string}
     * @memberof AclSid
     */
    id?: string;
    /**
     * UUID of owner of the object in the system
     * @type {string}
     * @memberof AclSid
     */
    ownerId?: string;
    /**
     * Date of object creation
     * @type {Date}
     * @memberof AclSid
     */
    createdDate?: Date;
    /**
     * Data, including hash of the key(s) used to encrypt this record.
     * @type {string}
     * @memberof AclSid
     */
    keyHash?: string;
    /**
     * Last user to access object
     * @type {string}
     * @memberof AclSid
     */
    lastAccessedById?: string;
    /**
     * Timestamp of last access of object
     * @type {Date}
     * @memberof AclSid
     */
    lastAccessedDate?: Date;
    /**
     * Unique identifier for user who last modifed the object in the system
     * @type {string}
     * @memberof AclSid
     */
    lastModifiedById?: string;
    /**
     * Date of last object modification
     * @type {Date}
     * @memberof AclSid
     */
    lastModifiedDate?: Date;
}

export function AclSidFromJSON(json: any): AclSid {
    return {
        'sid': !exists(json, 'sid') ? undefined : json['sid'],
        'principal': !exists(json, 'principal') ? undefined : json['principal'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'ownerId': !exists(json, 'ownerId') ? undefined : json['ownerId'],
        'createdDate': !exists(json, 'createdDate') ? undefined : new Date(json['createdDate']),
        'keyHash': !exists(json, 'keyHash') ? undefined : json['keyHash'],
        'lastAccessedById': !exists(json, 'lastAccessedById') ? undefined : json['lastAccessedById'],
        'lastAccessedDate': !exists(json, 'lastAccessedDate') ? undefined : new Date(json['lastAccessedDate']),
        'lastModifiedById': !exists(json, 'lastModifiedById') ? undefined : json['lastModifiedById'],
        'lastModifiedDate': !exists(json, 'lastModifiedDate') ? undefined : new Date(json['lastModifiedDate']),
    };
}

export function AclSidToJSON(value?: AclSid): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'sid': value.sid,
        'principal': value.principal,
        'id': value.id,
        'ownerId': value.ownerId,
        'createdDate': value.createdDate === undefined ? undefined : value.createdDate.toISOString(),
        'keyHash': value.keyHash,
        'lastAccessedById': value.lastAccessedById,
        'lastAccessedDate': value.lastAccessedDate === undefined ? undefined : value.lastAccessedDate.toISOString(),
        'lastModifiedById': value.lastModifiedById,
        'lastModifiedDate': value.lastModifiedDate === undefined ? undefined : value.lastModifiedDate.toISOString(),
    };
}


