// tslint:disable
/**
 * ValkyrAI CORE API
 * The API for accessing ValkyrAI services
 *
 * The version of the OpenAPI document: 0.9.25
 * Contact: info@valkyrlabs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../src/runtime';

// thorapi

/**
 * TODO Authority CLASS DESCRIPTION
 * @export
 * @interface Authority
 */
export type Authority  = {
    /**
     * 
     * @type {string}
     * @memberof Authority
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof Authority
     */
    authority: string;
    /**
     * 
     * @type {string}
     * @memberof Authority
     */
    principalId?: string;
    /**
     * Unique identifier for object in the system
     * @type {string}
     * @memberof Authority
     */
    id?: string;
    /**
     * UUID of owner of the object in the system
     * @type {string}
     * @memberof Authority
     */
    ownerId?: string;
    /**
     * Date of object creation
     * @type {Date}
     * @memberof Authority
     */
    createdDate?: Date;
    /**
     * Data, including hash of the key(s) used to encrypt this record.
     * @type {string}
     * @memberof Authority
     */
    keyHash?: string;
    /**
     * Last user to access object
     * @type {string}
     * @memberof Authority
     */
    lastAccessedById?: string;
    /**
     * Timestamp of last access of object
     * @type {Date}
     * @memberof Authority
     */
    lastAccessedDate?: Date;
    /**
     * Unique identifier for user who last modifed the object in the system
     * @type {string}
     * @memberof Authority
     */
    lastModifiedById?: string;
    /**
     * Date of last object modification
     * @type {Date}
     * @memberof Authority
     */
    lastModifiedDate?: Date;
}

export function AuthorityFromJSON(json: any): Authority {
    return {
        'username': json['username'],
        'authority': json['authority'],
        'principalId': !exists(json, 'principalId') ? undefined : json['principalId'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'ownerId': !exists(json, 'ownerId') ? undefined : json['ownerId'],
        'createdDate': !exists(json, 'createdDate') ? undefined : new Date(json['createdDate']),
        'keyHash': !exists(json, 'keyHash') ? undefined : json['keyHash'],
        'lastAccessedById': !exists(json, 'lastAccessedById') ? undefined : json['lastAccessedById'],
        'lastAccessedDate': !exists(json, 'lastAccessedDate') ? undefined : new Date(json['lastAccessedDate']),
        'lastModifiedById': !exists(json, 'lastModifiedById') ? undefined : json['lastModifiedById'],
        'lastModifiedDate': !exists(json, 'lastModifiedDate') ? undefined : new Date(json['lastModifiedDate']),
    };
}

export function AuthorityToJSON(value?: Authority): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'username': value.username,
        'authority': value.authority,
        'principalId': value.principalId,
        'id': value.id,
        'ownerId': value.ownerId,
        'createdDate': value.createdDate === undefined ? undefined : value.createdDate.toISOString(),
        'keyHash': value.keyHash,
        'lastAccessedById': value.lastAccessedById,
        'lastAccessedDate': value.lastAccessedDate === undefined ? undefined : value.lastAccessedDate.toISOString(),
        'lastModifiedById': value.lastModifiedById,
        'lastModifiedDate': value.lastModifiedDate === undefined ? undefined : value.lastModifiedDate.toISOString(),
    };
}


