// tslint:disable
/**
 * ValkyrAI CORE API
 * The API for accessing ValkyrAI services
 *
 * The version of the OpenAPI document: 0.9.25
 * Contact: info@valkyrlabs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../src/runtime';

// thorapi

/**
 * A Chat message sent to a recipient
 * @export
 * @interface ChatMessage
 */
export type ChatMessage  = {
    /**
     * 
     * @type {string}
     * @memberof ChatMessage
     */
    sessionId?: string;
    /**
     * if this chat message is conencted to a service (ws)
     * @type {boolean}
     * @memberof ChatMessage
     */
    connected?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ChatMessage
     */
    json?: string;
    /**
     * type of the message source
     * @type {string}
     * @memberof ChatMessage
     */
    sourceType?: ChatMessageSourceTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ChatMessage
     */
    sourceOwner?: string;
    /**
     * 
     * @type {string}
     * @memberof ChatMessage
     */
    role?: ChatMessageRoleEnum;
    /**
     * the message to send to the chat service
     * @type {string}
     * @memberof ChatMessage
     */
    content?: string;
    /**
     * Unique identifier for object in the system
     * @type {string}
     * @memberof ChatMessage
     */
    id?: string;
    /**
     * UUID of owner of the object in the system
     * @type {string}
     * @memberof ChatMessage
     */
    ownerId?: string;
    /**
     * Date of object creation
     * @type {Date}
     * @memberof ChatMessage
     */
    createdDate?: Date;
    /**
     * Data, including hash of the key(s) used to encrypt this record.
     * @type {string}
     * @memberof ChatMessage
     */
    keyHash?: string;
    /**
     * Last user to access object
     * @type {string}
     * @memberof ChatMessage
     */
    lastAccessedById?: string;
    /**
     * Timestamp of last access of object
     * @type {Date}
     * @memberof ChatMessage
     */
    lastAccessedDate?: Date;
    /**
     * Unique identifier for user who last modifed the object in the system
     * @type {string}
     * @memberof ChatMessage
     */
    lastModifiedById?: string;
    /**
     * Date of last object modification
     * @type {Date}
     * @memberof ChatMessage
     */
    lastModifiedDate?: Date;
}

export function ChatMessageFromJSON(json: any): ChatMessage {
    return {
        'sessionId': !exists(json, 'sessionId') ? undefined : json['sessionId'],
        'connected': !exists(json, 'connected') ? undefined : json['connected'],
        'json': !exists(json, 'json') ? undefined : json['json'],
        'sourceType': !exists(json, 'sourceType') ? undefined : json['sourceType'],
        'sourceOwner': !exists(json, 'sourceOwner') ? undefined : json['sourceOwner'],
        'role': !exists(json, 'role') ? undefined : json['role'],
        'content': !exists(json, 'content') ? undefined : json['content'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'ownerId': !exists(json, 'ownerId') ? undefined : json['ownerId'],
        'createdDate': !exists(json, 'createdDate') ? undefined : new Date(json['createdDate']),
        'keyHash': !exists(json, 'keyHash') ? undefined : json['keyHash'],
        'lastAccessedById': !exists(json, 'lastAccessedById') ? undefined : json['lastAccessedById'],
        'lastAccessedDate': !exists(json, 'lastAccessedDate') ? undefined : new Date(json['lastAccessedDate']),
        'lastModifiedById': !exists(json, 'lastModifiedById') ? undefined : json['lastModifiedById'],
        'lastModifiedDate': !exists(json, 'lastModifiedDate') ? undefined : new Date(json['lastModifiedDate']),
    };
}

export function ChatMessageToJSON(value?: ChatMessage): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'sessionId': value.sessionId,
        'connected': value.connected,
        'json': value.json,
        'sourceType': value.sourceType,
        'sourceOwner': value.sourceOwner,
        'role': value.role,
        'content': value.content,
        'id': value.id,
        'ownerId': value.ownerId,
        'createdDate': value.createdDate === undefined ? undefined : value.createdDate.toISOString(),
        'keyHash': value.keyHash,
        'lastAccessedById': value.lastAccessedById,
        'lastAccessedDate': value.lastAccessedDate === undefined ? undefined : value.lastAccessedDate.toISOString(),
        'lastModifiedById': value.lastModifiedById,
        'lastModifiedDate': value.lastModifiedDate === undefined ? undefined : value.lastModifiedDate.toISOString(),
    };
}

/**
* @export
* @enum {string}
*/
export enum ChatMessageSourceTypeEnum {
    API = 'api',
    SERVERLOG = 'server_log',
    P2P = 'p2p'
}
/**
* @export
* @enum {string}
*/
export enum ChatMessageRoleEnum {
    USER = 'user',
    ASSISTANT = 'assistant'
}


