// tslint:disable
/**
 * ValkyrAI CORE API
 * The API for accessing ValkyrAI services
 *
 * The version of the OpenAPI document: 0.9.25
 * Contact: info@valkyrlabs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../src/runtime';

// thorapi

/**
 * TODO LlmDetails CLASS DESCRIPTION
 * @export
 * @interface LlmDetails
 */
export type LlmDetails  = {
    /**
     * The name of the LLM
     * @type {string}
     * @memberof LlmDetails
     */
    name?: string;
    /**
     * The vendor-specific version of the LLM
     * @type {string}
     * @memberof LlmDetails
     */
    version?: string;
    /**
     * Notes on the LLM implementation
     * @type {string}
     * @memberof LlmDetails
     */
    notes?: string;
    /**
     * the user role to set for the target LLM
     * @type {string}
     * @memberof LlmDetails
     */
    role?: LlmDetailsRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof LlmDetails
     */
    provider?: LlmDetailsProviderEnum;
    /**
     * 
     * @type {string}
     * @memberof LlmDetails
     */
    apiType?: LlmDetailsApiTypeEnum;
    /**
     * the initial prompt to instruct the LLM how to behave
     * @type {string}
     * @memberof LlmDetails
     */
    initialPrompt?: string;
    /**
     * the api-key to access the llm
     * @type {string}
     * @memberof LlmDetails
     */
    apiKey?: string;
    /**
     * the user name to access the LLM
     * @type {string}
     * @memberof LlmDetails
     */
    credential?: string;
    /**
     * the password to access the LLM
     * @type {string}
     * @memberof LlmDetails
     */
    credentialPassword?: string;
    /**
     * the URL to connect to the LLM api
     * @type {string}
     * @memberof LlmDetails
     */
    url?: string;
    /**
     * request parameters to send to the service
     * @type {string}
     * @memberof LlmDetails
     */
    requestParameters?: string;
    /**
     * metadata in any text format to be used in client code
     * @type {string}
     * @memberof LlmDetails
     */
    meta?: string;
    /**
     * Unique identifier for object in the system
     * @type {string}
     * @memberof LlmDetails
     */
    id?: string;
    /**
     * UUID of owner of the object in the system
     * @type {string}
     * @memberof LlmDetails
     */
    ownerId?: string;
    /**
     * Date of object creation
     * @type {Date}
     * @memberof LlmDetails
     */
    createdDate?: Date;
    /**
     * Data, including hash of the key(s) used to encrypt this record.
     * @type {string}
     * @memberof LlmDetails
     */
    keyHash?: string;
    /**
     * Last user to access object
     * @type {string}
     * @memberof LlmDetails
     */
    lastAccessedById?: string;
    /**
     * Timestamp of last access of object
     * @type {Date}
     * @memberof LlmDetails
     */
    lastAccessedDate?: Date;
    /**
     * Unique identifier for user who last modifed the object in the system
     * @type {string}
     * @memberof LlmDetails
     */
    lastModifiedById?: string;
    /**
     * Date of last object modification
     * @type {Date}
     * @memberof LlmDetails
     */
    lastModifiedDate?: Date;
}

export function LlmDetailsFromJSON(json: any): LlmDetails {
    return {
        'name': !exists(json, 'name') ? undefined : json['name'],
        'version': !exists(json, 'version') ? undefined : json['version'],
        'notes': !exists(json, 'notes') ? undefined : json['notes'],
        'role': !exists(json, 'role') ? undefined : json['role'],
        'provider': !exists(json, 'provider') ? undefined : json['provider'],
        'apiType': !exists(json, 'apiType') ? undefined : json['apiType'],
        'initialPrompt': !exists(json, 'initialPrompt') ? undefined : json['initialPrompt'],
        'apiKey': !exists(json, 'apiKey') ? undefined : json['apiKey'],
        'credential': !exists(json, 'credential') ? undefined : json['credential'],
        'credentialPassword': !exists(json, 'credentialPassword') ? undefined : json['credentialPassword'],
        'url': !exists(json, 'url') ? undefined : json['url'],
        'requestParameters': !exists(json, 'requestParameters') ? undefined : json['requestParameters'],
        'meta': !exists(json, 'meta') ? undefined : json['meta'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'ownerId': !exists(json, 'ownerId') ? undefined : json['ownerId'],
        'createdDate': !exists(json, 'createdDate') ? undefined : new Date(json['createdDate']),
        'keyHash': !exists(json, 'keyHash') ? undefined : json['keyHash'],
        'lastAccessedById': !exists(json, 'lastAccessedById') ? undefined : json['lastAccessedById'],
        'lastAccessedDate': !exists(json, 'lastAccessedDate') ? undefined : new Date(json['lastAccessedDate']),
        'lastModifiedById': !exists(json, 'lastModifiedById') ? undefined : json['lastModifiedById'],
        'lastModifiedDate': !exists(json, 'lastModifiedDate') ? undefined : new Date(json['lastModifiedDate']),
    };
}

export function LlmDetailsToJSON(value?: LlmDetails): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'name': value.name,
        'version': value.version,
        'notes': value.notes,
        'role': value.role,
        'provider': value.provider,
        'apiType': value.apiType,
        'initialPrompt': value.initialPrompt,
        'apiKey': value.apiKey,
        'credential': value.credential,
        'credentialPassword': value.credentialPassword,
        'url': value.url,
        'requestParameters': value.requestParameters,
        'meta': value.meta,
        'id': value.id,
        'ownerId': value.ownerId,
        'createdDate': value.createdDate === undefined ? undefined : value.createdDate.toISOString(),
        'keyHash': value.keyHash,
        'lastAccessedById': value.lastAccessedById,
        'lastAccessedDate': value.lastAccessedDate === undefined ? undefined : value.lastAccessedDate.toISOString(),
        'lastModifiedById': value.lastModifiedById,
        'lastModifiedDate': value.lastModifiedDate === undefined ? undefined : value.lastModifiedDate.toISOString(),
    };
}

/**
* @export
* @enum {string}
*/
export enum LlmDetailsRoleEnum {
    USER = 'user',
    ASSISTANT = 'assistant'
}
/**
* @export
* @enum {string}
*/
export enum LlmDetailsProviderEnum {
    VALKYRAI = 'valkyrai',
    OPENAI = 'openai',
    LLAMA = 'llama',
    PHI = 'phi',
    GEMMA = 'gemma',
    MISTRAL = 'mistral',
    CLAUDE = 'claude',
    GEMINI = 'gemini',
    OTHER = 'other'
}
/**
* @export
* @enum {string}
*/
export enum LlmDetailsApiTypeEnum {
    OPENAI = 'openai',
    OLLAMA = 'ollama',
    OTHER = 'other'
}


