// tslint:disable
/**
 * Percival the Dragon Slayer CORE API
 * The API for accessing Percival the Dragon Slayer services
 *
 * The version of the OpenAPI document: 0.9.25
 * Contact: info@valkyrlabs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../src/runtime';
import {


    Cell,
    CellFromJSON,
    CellToJSON,
} from './';


// thorapi

/**
 * Sheetster Merged CellRange
 * @export
 * @interface MergeRange
 */
export type MergeRange  = {
    /**
     * the sheet containing this merged range
     * @type {string}
     * @memberof MergeRange
     */
    sheetId?: string;
    /**
     * 
     * @type {Cell}
     * @memberof MergeRange
     */
    startCell?: Cell;
    /**
     * 
     * @type {Cell}
     * @memberof MergeRange
     */
    endCell?: Cell;
    /**
     * Unique identifier for object in the system
     * @type {string}
     * @memberof MergeRange
     */
    id?: string;
    /**
     * UUID of owner of the object in the system
     * @type {string}
     * @memberof MergeRange
     */
    ownerId?: string;
    /**
     * Date of object creation
     * @type {Date}
     * @memberof MergeRange
     */
    createdDate?: Date;
    /**
     * Data, including hash of the key(s) used to encrypt this record.
     * @type {string}
     * @memberof MergeRange
     */
    keyHash?: string;
    /**
     * Last user to access object
     * @type {string}
     * @memberof MergeRange
     */
    lastAccessedById?: string;
    /**
     * Timestamp of last access of object
     * @type {Date}
     * @memberof MergeRange
     */
    lastAccessedDate?: Date;
    /**
     * Unique identifier for user who last modifed the object in the system
     * @type {string}
     * @memberof MergeRange
     */
    lastModifiedById?: string;
    /**
     * Date of last object modification
     * @type {Date}
     * @memberof MergeRange
     */
    lastModifiedDate?: Date;
}

export function MergeRangeFromJSON(json: any): MergeRange {
    return {
        'sheetId': !exists(json, 'sheetId') ? undefined : json['sheetId'],
        'startCell': !exists(json, 'startCell') ? undefined : CellFromJSON(json['startCell']),
        'endCell': !exists(json, 'endCell') ? undefined : CellFromJSON(json['endCell']),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'ownerId': !exists(json, 'ownerId') ? undefined : json['ownerId'],
        'createdDate': !exists(json, 'createdDate') ? undefined : new Date(json['createdDate']),
        'keyHash': !exists(json, 'keyHash') ? undefined : json['keyHash'],
        'lastAccessedById': !exists(json, 'lastAccessedById') ? undefined : json['lastAccessedById'],
        'lastAccessedDate': !exists(json, 'lastAccessedDate') ? undefined : new Date(json['lastAccessedDate']),
        'lastModifiedById': !exists(json, 'lastModifiedById') ? undefined : json['lastModifiedById'],
        'lastModifiedDate': !exists(json, 'lastModifiedDate') ? undefined : new Date(json['lastModifiedDate']),
    };
}

export function MergeRangeToJSON(value?: MergeRange): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'sheetId': value.sheetId,
        'startCell': CellToJSON(value.startCell),
        'endCell': CellToJSON(value.endCell),
        'id': value.id,
        'ownerId': value.ownerId,
        'createdDate': value.createdDate === undefined ? undefined : value.createdDate.toISOString(),
        'keyHash': value.keyHash,
        'lastAccessedById': value.lastAccessedById,
        'lastAccessedDate': value.lastAccessedDate === undefined ? undefined : value.lastAccessedDate.toISOString(),
        'lastModifiedById': value.lastModifiedById,
        'lastModifiedDate': value.lastModifiedDate === undefined ? undefined : value.lastModifiedDate.toISOString(),
    };
}


