// tslint:disable
/**
 * ValkyrAI CORE API
 * The API for accessing ValkyrAI services
 *
 * The version of the OpenAPI document: 0.9.25
 * Contact: info@valkyrlabs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../src/runtime';

// thorapi

/**
 * Represents a sales activity or engagement related to an opportunity.
 * @export
 * @interface SalesActivity
 */
export type SalesActivity  = {
    /**
     * The associated opportunity.
     * @type {string}
     * @memberof SalesActivity
     */
    opportunityId: string;
    /**
     * Type of the sales activity.
     * @type {string}
     * @memberof SalesActivity
     */
    type: SalesActivityTypeEnum;
    /**
     * Date and time of the activity.
     * @type {Date}
     * @memberof SalesActivity
     */
    activityDate: Date;
    /**
     * The user who performed the activity.
     * @type {string}
     * @memberof SalesActivity
     */
    performedBy: string;
    /**
     * Details about the activity.
     * @type {string}
     * @memberof SalesActivity
     */
    details?: string;
    /**
     * Unique identifier for object in the system
     * @type {string}
     * @memberof SalesActivity
     */
    id?: string;
    /**
     * UUID of owner of the object in the system
     * @type {string}
     * @memberof SalesActivity
     */
    ownerId?: string;
    /**
     * Date of object creation
     * @type {Date}
     * @memberof SalesActivity
     */
    createdDate?: Date;
    /**
     * Data, including hash of the key(s) used to encrypt this record.
     * @type {string}
     * @memberof SalesActivity
     */
    keyHash?: string;
    /**
     * Last user to access object
     * @type {string}
     * @memberof SalesActivity
     */
    lastAccessedById?: string;
    /**
     * Timestamp of last access of object
     * @type {Date}
     * @memberof SalesActivity
     */
    lastAccessedDate?: Date;
    /**
     * Unique identifier for user who last modifed the object in the system
     * @type {string}
     * @memberof SalesActivity
     */
    lastModifiedById?: string;
    /**
     * Date of last object modification
     * @type {Date}
     * @memberof SalesActivity
     */
    lastModifiedDate?: Date;
}

export function SalesActivityFromJSON(json: any): SalesActivity {
    return {
        'opportunityId': json['opportunityId'],
        'type': json['type'],
        'activityDate': new Date(json['activityDate']),
        'performedBy': json['performedBy'],
        'details': !exists(json, 'details') ? undefined : json['details'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'ownerId': !exists(json, 'ownerId') ? undefined : json['ownerId'],
        'createdDate': !exists(json, 'createdDate') ? undefined : new Date(json['createdDate']),
        'keyHash': !exists(json, 'keyHash') ? undefined : json['keyHash'],
        'lastAccessedById': !exists(json, 'lastAccessedById') ? undefined : json['lastAccessedById'],
        'lastAccessedDate': !exists(json, 'lastAccessedDate') ? undefined : new Date(json['lastAccessedDate']),
        'lastModifiedById': !exists(json, 'lastModifiedById') ? undefined : json['lastModifiedById'],
        'lastModifiedDate': !exists(json, 'lastModifiedDate') ? undefined : new Date(json['lastModifiedDate']),
    };
}

export function SalesActivityToJSON(value?: SalesActivity): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'opportunityId': value.opportunityId,
        'type': value.type,
        'activityDate': value.activityDate.toISOString(),
        'performedBy': value.performedBy,
        'details': value.details,
        'id': value.id,
        'ownerId': value.ownerId,
        'createdDate': value.createdDate === undefined ? undefined : value.createdDate.toISOString(),
        'keyHash': value.keyHash,
        'lastAccessedById': value.lastAccessedById,
        'lastAccessedDate': value.lastAccessedDate === undefined ? undefined : value.lastAccessedDate.toISOString(),
        'lastModifiedById': value.lastModifiedById,
        'lastModifiedDate': value.lastModifiedDate === undefined ? undefined : value.lastModifiedDate.toISOString(),
    };
}

/**
* @export
* @enum {string}
*/
export enum SalesActivityTypeEnum {
    CALL = 'call',
    MEETING = 'meeting',
    EMAIL = 'email',
    FOLLOWUP = 'follow-up'
}


