// tslint:disable
/**
 * ValkyrAI CORE API
 * The API for accessing ValkyrAI services
 *
 * The version of the OpenAPI document: 0.9.25
 * Contact: info@valkyrlabs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../src/runtime';

// thorapi

/**
 * Represents the stages in a sales pipeline.
 * @export
 * @interface SalesPipeline
 */
export type SalesPipeline  = {
    /**
     * Name of the sales stage (e.g., Lead, Qualification, Proposal, Negotiation, Closed).
     * @type {string}
     * @memberof SalesPipeline
     */
    name: SalesPipelineNameEnum;
    /**
     * The order in which the stages are followed in the sales process.
     * @type {number}
     * @memberof SalesPipeline
     */
    sequenceOrder?: number;
    /**
     * Unique identifier for object in the system
     * @type {string}
     * @memberof SalesPipeline
     */
    id?: string;
    /**
     * UUID of owner of the object in the system
     * @type {string}
     * @memberof SalesPipeline
     */
    ownerId?: string;
    /**
     * Date of object creation
     * @type {Date}
     * @memberof SalesPipeline
     */
    createdDate?: Date;
    /**
     * Data, including hash of the key(s) used to encrypt this record.
     * @type {string}
     * @memberof SalesPipeline
     */
    keyHash?: string;
    /**
     * Last user to access object
     * @type {string}
     * @memberof SalesPipeline
     */
    lastAccessedById?: string;
    /**
     * Timestamp of last access of object
     * @type {Date}
     * @memberof SalesPipeline
     */
    lastAccessedDate?: Date;
    /**
     * Unique identifier for user who last modifed the object in the system
     * @type {string}
     * @memberof SalesPipeline
     */
    lastModifiedById?: string;
    /**
     * Date of last object modification
     * @type {Date}
     * @memberof SalesPipeline
     */
    lastModifiedDate?: Date;
}

export function SalesPipelineFromJSON(json: any): SalesPipeline {
    return {
        'name': json['name'],
        'sequenceOrder': !exists(json, 'sequenceOrder') ? undefined : json['sequenceOrder'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'ownerId': !exists(json, 'ownerId') ? undefined : json['ownerId'],
        'createdDate': !exists(json, 'createdDate') ? undefined : new Date(json['createdDate']),
        'keyHash': !exists(json, 'keyHash') ? undefined : json['keyHash'],
        'lastAccessedById': !exists(json, 'lastAccessedById') ? undefined : json['lastAccessedById'],
        'lastAccessedDate': !exists(json, 'lastAccessedDate') ? undefined : new Date(json['lastAccessedDate']),
        'lastModifiedById': !exists(json, 'lastModifiedById') ? undefined : json['lastModifiedById'],
        'lastModifiedDate': !exists(json, 'lastModifiedDate') ? undefined : new Date(json['lastModifiedDate']),
    };
}

export function SalesPipelineToJSON(value?: SalesPipeline): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'name': value.name,
        'sequenceOrder': value.sequenceOrder,
        'id': value.id,
        'ownerId': value.ownerId,
        'createdDate': value.createdDate === undefined ? undefined : value.createdDate.toISOString(),
        'keyHash': value.keyHash,
        'lastAccessedById': value.lastAccessedById,
        'lastAccessedDate': value.lastAccessedDate === undefined ? undefined : value.lastAccessedDate.toISOString(),
        'lastModifiedById': value.lastModifiedById,
        'lastModifiedDate': value.lastModifiedDate === undefined ? undefined : value.lastModifiedDate.toISOString(),
    };
}

/**
* @export
* @enum {string}
*/
export enum SalesPipelineNameEnum {
    LEAD = 'lead',
    QUALIFICATION = 'qualification',
    PROPOSAL = 'proposal',
    NEGOTIATION = 'negotiation',
    CLOSED = 'closed'
}


