// tslint:disable
/**
 * ValkyrAI CORE API
 * The API for accessing ValkyrAI services
 *
 * The version of the OpenAPI document: 0.9.25
 * Contact: info@valkyrlabs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../src/runtime';

// thorapi

/**
 * TODO Solution CLASS DESCRIPTION
 * @export
 * @interface Solution
 */
export type Solution  = {
    /**
     * 
     * @type {string}
     * @memberof Solution
     */
    buildOutputId: string;
    /**
     * 
     * @type {string}
     * @memberof Solution
     */
    description: string;
    /**
     * 
     * @type {boolean}
     * @memberof Solution
     */
    appliedFix: boolean;
    /**
     * Unique identifier for object in the system
     * @type {string}
     * @memberof Solution
     */
    id?: string;
    /**
     * UUID of owner of the object in the system
     * @type {string}
     * @memberof Solution
     */
    ownerId?: string;
    /**
     * Date of object creation
     * @type {Date}
     * @memberof Solution
     */
    createdDate?: Date;
    /**
     * Data, including hash of the key(s) used to encrypt this record.
     * @type {string}
     * @memberof Solution
     */
    keyHash?: string;
    /**
     * Last user to access object
     * @type {string}
     * @memberof Solution
     */
    lastAccessedById?: string;
    /**
     * Timestamp of last access of object
     * @type {Date}
     * @memberof Solution
     */
    lastAccessedDate?: Date;
    /**
     * Unique identifier for user who last modifed the object in the system
     * @type {string}
     * @memberof Solution
     */
    lastModifiedById?: string;
    /**
     * Date of last object modification
     * @type {Date}
     * @memberof Solution
     */
    lastModifiedDate?: Date;
}

export function SolutionFromJSON(json: any): Solution {
    return {
        'buildOutputId': json['buildOutputId'],
        'description': json['description'],
        'appliedFix': json['appliedFix'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'ownerId': !exists(json, 'ownerId') ? undefined : json['ownerId'],
        'createdDate': !exists(json, 'createdDate') ? undefined : new Date(json['createdDate']),
        'keyHash': !exists(json, 'keyHash') ? undefined : json['keyHash'],
        'lastAccessedById': !exists(json, 'lastAccessedById') ? undefined : json['lastAccessedById'],
        'lastAccessedDate': !exists(json, 'lastAccessedDate') ? undefined : new Date(json['lastAccessedDate']),
        'lastModifiedById': !exists(json, 'lastModifiedById') ? undefined : json['lastModifiedById'],
        'lastModifiedDate': !exists(json, 'lastModifiedDate') ? undefined : new Date(json['lastModifiedDate']),
    };
}

export function SolutionToJSON(value?: Solution): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'buildOutputId': value.buildOutputId,
        'description': value.description,
        'appliedFix': value.appliedFix,
        'id': value.id,
        'ownerId': value.ownerId,
        'createdDate': value.createdDate === undefined ? undefined : value.createdDate.toISOString(),
        'keyHash': value.keyHash,
        'lastAccessedById': value.lastAccessedById,
        'lastAccessedDate': value.lastAccessedDate === undefined ? undefined : value.lastAccessedDate.toISOString(),
        'lastModifiedById': value.lastModifiedById,
        'lastModifiedDate': value.lastModifiedDate === undefined ? undefined : value.lastModifiedDate.toISOString(),
    };
}


