// tslint:disable
/**
 * ValkyrAI CORE API
 * The API for accessing ValkyrAI services
 *
 * The version of the OpenAPI document: 0.9.25
 * Contact: info@valkyrlabs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../src/runtime';

// thorapi

/**
 * Various System User Preferences
 * @export
 * @interface UserPreferences
 */
export type UserPreferences  = {
    /**
     * The value of the User Preferences
     * @type {string}
     * @memberof UserPreferences
     */
    preference?: string;
    /**
     * The type of the preference
     * @type {string}
     * @memberof UserPreferences
     */
    preferenceType?: UserPreferencesPreferenceTypeEnum;
    /**
     * Unique identifier for object in the system
     * @type {string}
     * @memberof UserPreferences
     */
    id?: string;
    /**
     * UUID of owner of the object in the system
     * @type {string}
     * @memberof UserPreferences
     */
    ownerId?: string;
    /**
     * Date of object creation
     * @type {Date}
     * @memberof UserPreferences
     */
    createdDate?: Date;
    /**
     * Data, including hash of the key(s) used to encrypt this record.
     * @type {string}
     * @memberof UserPreferences
     */
    keyHash?: string;
    /**
     * Last user to access object
     * @type {string}
     * @memberof UserPreferences
     */
    lastAccessedById?: string;
    /**
     * Timestamp of last access of object
     * @type {Date}
     * @memberof UserPreferences
     */
    lastAccessedDate?: Date;
    /**
     * Unique identifier for user who last modifed the object in the system
     * @type {string}
     * @memberof UserPreferences
     */
    lastModifiedById?: string;
    /**
     * Date of last object modification
     * @type {Date}
     * @memberof UserPreferences
     */
    lastModifiedDate?: Date;
}

export function UserPreferencesFromJSON(json: any): UserPreferences {
    return {
        'preference': !exists(json, 'preference') ? undefined : json['preference'],
        'preferenceType': !exists(json, 'preferenceType') ? undefined : json['preferenceType'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'ownerId': !exists(json, 'ownerId') ? undefined : json['ownerId'],
        'createdDate': !exists(json, 'createdDate') ? undefined : new Date(json['createdDate']),
        'keyHash': !exists(json, 'keyHash') ? undefined : json['keyHash'],
        'lastAccessedById': !exists(json, 'lastAccessedById') ? undefined : json['lastAccessedById'],
        'lastAccessedDate': !exists(json, 'lastAccessedDate') ? undefined : new Date(json['lastAccessedDate']),
        'lastModifiedById': !exists(json, 'lastModifiedById') ? undefined : json['lastModifiedById'],
        'lastModifiedDate': !exists(json, 'lastModifiedDate') ? undefined : new Date(json['lastModifiedDate']),
    };
}

export function UserPreferencesToJSON(value?: UserPreferences): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'preference': value.preference,
        'preferenceType': value.preferenceType,
        'id': value.id,
        'ownerId': value.ownerId,
        'createdDate': value.createdDate === undefined ? undefined : value.createdDate.toISOString(),
        'keyHash': value.keyHash,
        'lastAccessedById': value.lastAccessedById,
        'lastAccessedDate': value.lastAccessedDate === undefined ? undefined : value.lastAccessedDate.toISOString(),
        'lastModifiedById': value.lastModifiedById,
        'lastModifiedDate': value.lastModifiedDate === undefined ? undefined : value.lastModifiedDate.toISOString(),
    };
}

/**
* @export
* @enum {string}
*/
export enum UserPreferencesPreferenceTypeEnum {
    UXLAYOUT = 'ux-layout',
    UXMODE = 'ux-mode',
    UXTHEME = 'ux-theme',
    MEASUREMENT = 'measurement'
}


