// tslint:disable

/**
############################## DO NOT EDIT: GENERATED FILE ##############################

Generated by Valkyr Labs ThorAPI: https://valkyrlabs.com

Powered by Swagger Codegen: http://swagger.io

Generator version: (7.5.0)

Template file: typescript-redux-query/apis.mustache

############################## DO NOT EDIT: GENERATED FILE ##############################

Description: SecureKeyApi
*/

import { HttpMethods, QueryConfig, ResponseBody, ResponseText } from 'redux-query';
import * as runtime from '../src/runtime';
import {
    SecureKey,
    SecureKeyFromJSON,
    SecureKeyToJSON,
} from '../model';

export interface DeleteSecureKeyRequest {
    id: string;
}

export interface GetSecureKeyRequest {
    id: string;
}

export interface PostSecureKeyRequest {
    secureKey: SecureKey;
}

export interface UpdateSecureKeyRequest {
    id: string;
    secureKey: SecureKey;
}


/**
 * Deletes a specific SecureKey.
 * Delete a SecureKey.
 */
function deleteSecureKeyRaw<T>(requestParameters: DeleteSecureKeyRequest, requestConfig: runtime.TypedQueryConfig<T, void> = {}): QueryConfig<T> {
    if (requestParameters.id === null || requestParameters.id === undefined) {
        throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling deleteSecureKey.');
    }

    let queryParameters = null;


    const headerParameters : runtime.HttpHeaders = {};


    const { meta = {} } = requestConfig;

    const config: QueryConfig<T> = {
        url: `${runtime.Configuration.basePath}/SecureKey/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
        meta,
        update: requestConfig.update,
        queryKey: requestConfig.queryKey,
        optimisticUpdate: requestConfig.optimisticUpdate,
        force: requestConfig.force,
        rollback: requestConfig.rollback,
        options: {
            method: 'DELETE',
            headers: headerParameters,
        },
        body: queryParameters,
    };

    const { transform: requestTransform } = requestConfig;
    if (requestTransform) {
    }

    return config;
}

/**
* Deletes a specific SecureKey.
* Delete a SecureKey.
*/
export function deleteSecureKey<T>(requestParameters: DeleteSecureKeyRequest, requestConfig?: runtime.TypedQueryConfig<T, void>): QueryConfig<T> {
    return deleteSecureKeyRaw(requestParameters, requestConfig);
}

/**
 * Retrieves a single SecureKey for a specific uid.
 * Retrieve a single SecureKey
 */
function getSecureKeyRaw<T>(requestParameters: GetSecureKeyRequest, requestConfig: runtime.TypedQueryConfig<T, SecureKey> = {}): QueryConfig<T> {
    if (requestParameters.id === null || requestParameters.id === undefined) {
        throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling getSecureKey.');
    }

    let queryParameters = null;


    const headerParameters : runtime.HttpHeaders = {};


    const { meta = {} } = requestConfig;

    const config: QueryConfig<T> = {
        url: `${runtime.Configuration.basePath}/SecureKey/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
        meta,
        update: requestConfig.update,
        queryKey: requestConfig.queryKey,
        optimisticUpdate: requestConfig.optimisticUpdate,
        force: requestConfig.force,
        rollback: requestConfig.rollback,
        options: {
            method: 'GET',
            headers: headerParameters,
        },
        body: queryParameters,
    };

    const { transform: requestTransform } = requestConfig;
    if (requestTransform) {
        config.transform = (body: ResponseBody, text: ResponseBody) => requestTransform(SecureKeyFromJSON(body), text);
    }

    return config;
}

/**
* Retrieves a single SecureKey for a specific uid.
* Retrieve a single SecureKey
*/
export function getSecureKey<T>(requestParameters: GetSecureKeyRequest, requestConfig?: runtime.TypedQueryConfig<T, SecureKey>): QueryConfig<T> {
    return getSecureKeyRaw(requestParameters, requestConfig);
}

/**
 * Retrieves a list of SecureKeys.
 * Retrieve a list of SecureKeys
 */
function getSecureKeyListRaw<T>( requestConfig: runtime.TypedQueryConfig<T, Array<SecureKey>> = {}): QueryConfig<T> {
    let queryParameters = null;


    const headerParameters : runtime.HttpHeaders = {};


    const { meta = {} } = requestConfig;

    const config: QueryConfig<T> = {
        url: `${runtime.Configuration.basePath}/SecureKey`,
        meta,
        update: requestConfig.update,
        queryKey: requestConfig.queryKey,
        optimisticUpdate: requestConfig.optimisticUpdate,
        force: requestConfig.force,
        rollback: requestConfig.rollback,
        options: {
            method: 'GET',
            headers: headerParameters,
        },
        body: queryParameters,
    };

    const { transform: requestTransform } = requestConfig;
    if (requestTransform) {
        config.transform = (body: ResponseBody, text: ResponseBody) => requestTransform(body.map(SecureKeyFromJSON), text);
    }

    return config;
}

/**
* Retrieves a list of SecureKeys.
* Retrieve a list of SecureKeys
*/
export function getSecureKeyList<T>( requestConfig?: runtime.TypedQueryConfig<T, Array<SecureKey>>): QueryConfig<T> {
    return getSecureKeyListRaw( requestConfig);
}

/**
 * Creates a new SecureKey.
 * Create a new SecureKey
 */
function postSecureKeyRaw<T>(requestParameters: PostSecureKeyRequest, requestConfig: runtime.TypedQueryConfig<T, SecureKey> = {}): QueryConfig<T> {
    if (requestParameters.secureKey === null || requestParameters.secureKey === undefined) {
        throw new runtime.RequiredError('secureKey','Required parameter requestParameters.secureKey was null or undefined when calling postSecureKey.');
    }

    let queryParameters = null;


    const headerParameters : runtime.HttpHeaders = {};

    headerParameters['Content-Type'] = 'application/json';


    const { meta = {} } = requestConfig;

    const config: QueryConfig<T> = {
        url: `${runtime.Configuration.basePath}/SecureKey`,
        meta,
        update: requestConfig.update,
        queryKey: requestConfig.queryKey,
        optimisticUpdate: requestConfig.optimisticUpdate,
        force: requestConfig.force,
        rollback: requestConfig.rollback,
        options: {
            method: 'POST',
            headers: headerParameters,
        },
        body: queryParameters || SecureKeyToJSON(requestParameters.secureKey),
    };

    const { transform: requestTransform } = requestConfig;
    if (requestTransform) {
        config.transform = (body: ResponseBody, text: ResponseBody) => requestTransform(SecureKeyFromJSON(body), text);
    }

    return config;
}

/**
* Creates a new SecureKey.
* Create a new SecureKey
*/
export function postSecureKey<T>(requestParameters: PostSecureKeyRequest, requestConfig?: runtime.TypedQueryConfig<T, SecureKey>): QueryConfig<T> {
    return postSecureKeyRaw(requestParameters, requestConfig);
}

/**
 * Updates an existing SecureKey.
 * Update an existing SecureKey
 */
function updateSecureKeyRaw<T>(requestParameters: UpdateSecureKeyRequest, requestConfig: runtime.TypedQueryConfig<T, SecureKey> = {}): QueryConfig<T> {
    if (requestParameters.id === null || requestParameters.id === undefined) {
        throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling updateSecureKey.');
    }

    if (requestParameters.secureKey === null || requestParameters.secureKey === undefined) {
        throw new runtime.RequiredError('secureKey','Required parameter requestParameters.secureKey was null or undefined when calling updateSecureKey.');
    }

    let queryParameters = null;


    const headerParameters : runtime.HttpHeaders = {};

    headerParameters['Content-Type'] = 'application/json';


    const { meta = {} } = requestConfig;

    const config: QueryConfig<T> = {
        url: `${runtime.Configuration.basePath}/SecureKey/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
        meta,
        update: requestConfig.update,
        queryKey: requestConfig.queryKey,
        optimisticUpdate: requestConfig.optimisticUpdate,
        force: requestConfig.force,
        rollback: requestConfig.rollback,
        options: {
            method: 'PUT',
            headers: headerParameters,
        },
        body: queryParameters || SecureKeyToJSON(requestParameters.secureKey),
    };

    const { transform: requestTransform } = requestConfig;
    if (requestTransform) {
        config.transform = (body: ResponseBody, text: ResponseBody) => requestTransform(SecureKeyFromJSON(body), text);
    }

    return config;
}

/**
* Updates an existing SecureKey.
* Update an existing SecureKey
*/
export function updateSecureKey<T>(requestParameters: UpdateSecureKeyRequest, requestConfig?: runtime.TypedQueryConfig<T, SecureKey>): QueryConfig<T> {
    return updateSecureKeyRaw(requestParameters, requestConfig);
}

